In [2]:
from sklearn.decompositon import NMF

ModuleNotFoundError: No module named 'sklearn.decompositon'

In [5]:
from sklearn.decomposition import NMF
from numpy import nan as NA

In [8]:
import numpy as np
import pandas as pd
import time

In [9]:
R = np.array([
        [5, 3, NA, 1],
        [4, NA, NA, 1],
        [1, 1, NA, 5],
        [1, NA, NA, 4],
        [NA, 1, 5, 4],
        ]
    )

# 特徴の次元kを1から3まで変えてみる
for k in range(1,4):
    model = NMF(n_components=k, solver='mu', init='random', random_state=0)
    P = model.fit_transform(R)
    Q = model.components_
    print("****************************")
    print("k:",k)
    print("Pは")
    print(P)
    print("Q^Tは")
    print(Q)
    print("P×Q^Tは")
    print(np.dot(P,Q))
    print("R-P×Q^Tは")
    print(model.reconstruction_err_ )

****************************
k: 1
Pは
[[ 1.11230683]
 [ 0.83501252]
 [ 0.95442013]
 [ 0.82847958]
 [ 1.19620409]]
Q^Tは
[[ 3.02525029  1.53324123  4.17988875  2.98592215]]
P×Q^Tは
[[ 3.36500655  1.70543469  4.64931879  3.32126159]
 [ 2.52612188  1.28027563  3.49025945  2.49328239]
 [ 2.88735977  1.46335629  3.98936995  2.8498242 ]
 [ 2.50635809  1.27025905  3.46295247  2.47377553]
 [ 3.61881676  1.83406943  5.          3.57177228]]
R-P×Q^Tは
5.29312533898
****************************
k: 2
Pは
[[ 0.25533737  2.31920431]
 [ 0.2749493   1.8405892 ]
 [ 1.74751251  0.10992921]
 [ 1.39405084  0.18346339]
 [ 1.39101969  0.25440826]]
Q^Tは
[[ 0.43984129  0.49350833  3.05253861  2.85396988]
 [ 2.10749104  1.23916027  2.96318486  0.11698132]]
P×Q^Tは
[[ 5.00001021  2.99987694  7.65165828  1.00002874]
 [ 3.99995931  2.41647477  6.29329943  1.00001158]
 [ 1.00030298  0.99863188  5.66008999  5.00020773]
 [ 0.99980858  0.91531625  4.79902998  4.00004091]
 [ 1.14799101  1.0017324   5.          3.9996893 ]]


In [10]:
def mk_mat(df):
    

In [ ]:
for i in range(df['user_id'])